# Copyright (c) 2025 WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "idetraceprovider"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Observability", "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/module-ballerinax-idetraceprovider"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/idetraceprovider-native-@project.version@.jar"
groupId = "io.ballerina.lib"
artifactId = "idetraceprovider-native"
version = "@toml.version@"

# OpenTelemetry SDK (Core dependencies - transitive deps will be included via Gradle)
[[platform.java21.dependency]]
path = "./lib/opentelemetry-sdk-trace-@opentelemetrySDK.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "@opentelemetrySDK.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-sdk-common-@opentelemetrySDK.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "@opentelemetrySDK.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-sdk-@opentelemetrySDK.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk"
version = "@opentelemetrySDK.version@"

# OpenTelemetry Semconv
[[platform.java21.dependency]]
path = "./lib/opentelemetry-semconv-@opentelemetrySemconv.version@.jar"
groupId = "io.opentelemetry.semconv"
artifactId = "opentelemetry-semconv"
version = "@opentelemetrySemconv.version@"

# OTLP Exporter
[[platform.java21.dependency]]
path = "./lib/opentelemetry-exporter-otlp-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-otlp"
version = "@opentelemetry.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-exporter-common-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-common"
version = "@opentelemetry.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-exporter-otlp-common-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-otlp-common"
version = "@opentelemetry.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-exporter-sender-okhttp-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-sender-okhttp"
version = "@opentelemetry.version@"

# OpenTelemetry API & Context (needed at runtime)
[[platform.java21.dependency]]
path = "./lib/opentelemetry-api-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-api"
version = "@opentelemetry.version@"

[[platform.java21.dependency]]
path = "./lib/opentelemetry-context-@opentelemetry.version@.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-context"
version = "@opentelemetry.version@"

# OkHttp (HTTP Client)
[[platform.java21.dependency]]
path = "./lib/okhttp-@okHttp.version@.jar"
groupId = "com.squareup.okhttp3"
artifactId = "okhttp"
version = "@okHttp.version@"

[[platform.java21.dependency]]
path = "./lib/okio-jvm-@okio.version@.jar"
groupId = "com.squareup.okio"
artifactId = "okio-jvm"
version = "@okio.version@"

# Kotlin (required by OkHttp)
[[platform.java21.dependency]]
path = "./lib/kotlin-stdlib-@kotlin.version@.jar"
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version = "@kotlin.version@"
